### ISSUE TITLE
12.0.0-beta version please

### ISSUE THREAD

**Issue by yowl** [microsoft/LLVMSharp#143]
Hi, emscripten runs top-of-tree llvm which is now llvm 12.  Can we have a corresponding llvmsharp nuget please?

**Comment by tannergooding** [comment]
I don't think keeping LLVMSharp up to date with top-of-tree will be sustainable. The managed bindings, native bindings, and any helper libraries all need to match very exactly otherwise various ABI issues tend to crop up causing sporadic failures or hard to diagnose issues.

Trying to keep up to date with the previews, if any, might be somewhat possible, but LLVM tends to only tag/preview release candidates.

**Comment by yowl** [comment]
Ok, understand.  When I start asking questions to the emscripten people, one of the things they ask is "did you build your LLVM with the same version that emscripten uses", so keeping LLVMSharp as close as possible helps to alleviate that problem.

**Comment by tannergooding** [comment]
I would be happy to take contributions that make it easier to build/use LLVMSharp locally against a specific build of LLVM.
